

DROP TABLE IF EXISTS `EVENTLOG`;
CREATE TABLE `EVENTLOG` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CASE_ID` char(36) NOT NULL,
  `ACTIVITY_NAME` varchar(255) NOT NULL,
  `EVENT_TYPE` varchar(255) DEFAULT NULL,
  `RESOURCE` varchar(255) DEFAULT NULL,
  `RESOURCE_TYPE` varchar(255) DEFAULT NULL,
  `LIFECYCLE_PHASE` varchar(255) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REMARKS` json DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

